apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: dedalus-operators
  namespace: openshift-logging
  labels:
    app: dedalus-logging
    component: operator-group
spec: {}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: openshift-logging
  labels:
    app: dedalus-logging
    component: elasticsearch-operator
spec:
  channel: dedalus
  installPlanApproval: Automatic
  name: elasticsearch-operator
  source: dedalus-operators
  sourceNamespace: openshift-marketplace