apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
  labels:
    app: dedalus-logging
    component: forwarder
spec:
  outputDefaults:
    elasticsearch:
      structuredTypeKey: kubernetes.namespace_name
      structuredTypeName: nologformat
  pipelines:
    - inputRefs:
        - application
      name: application-json
      outputRefs:
        - default
      parse: json
    - inputRefs:
        - infrastructure
        - audit
      name: default-logging
      outputRefs:
        - default
